# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import darcy_pb2 as darcy__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in darcy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class pimlStub(object):
    """The request message containing the user's name.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_residual = channel.unary_unary(
                '/piml/get_residual',
                request_serializer=darcy__pb2.Array.SerializeToString,
                response_deserializer=darcy__pb2.Array.FromString,
                _registered_method=True)


class pimlServicer(object):
    """The request message containing the user's name.
    """

    def get_residual(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pimlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_residual': grpc.unary_unary_rpc_method_handler(
                    servicer.get_residual,
                    request_deserializer=darcy__pb2.Array.FromString,
                    response_serializer=darcy__pb2.Array.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'piml', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('piml', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class piml(object):
    """The request message containing the user's name.
    """

    @staticmethod
    def get_residual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/piml/get_residual',
            darcy__pb2.Array.SerializeToString,
            darcy__pb2.Array.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
