// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: darcy.proto

#include "darcy.pb.h"
#include "darcy.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* piml_method_names[] = {
  "/piml/get_residual",
};

std::unique_ptr< piml::Stub> piml::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< piml::Stub> stub(new piml::Stub(channel, options));
  return stub;
}

piml::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_get_residual_(piml_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status piml::Stub::get_residual(::grpc::ClientContext* context, const ::Array& request, ::Array* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Array, ::Array, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_residual_, context, request, response);
}

void piml::Stub::async::get_residual(::grpc::ClientContext* context, const ::Array* request, ::Array* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Array, ::Array, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_residual_, context, request, response, std::move(f));
}

void piml::Stub::async::get_residual(::grpc::ClientContext* context, const ::Array* request, ::Array* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_residual_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Array>* piml::Stub::PrepareAsyncget_residualRaw(::grpc::ClientContext* context, const ::Array& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Array, ::Array, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_residual_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Array>* piml::Stub::Asyncget_residualRaw(::grpc::ClientContext* context, const ::Array& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_residualRaw(context, request, cq);
  result->StartCall();
  return result;
}

piml::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      piml_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< piml::Service, ::Array, ::Array, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](piml::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Array* req,
             ::Array* resp) {
               return service->get_residual(ctx, req, resp);
             }, this)));
}

piml::Service::~Service() {
}

::grpc::Status piml::Service::get_residual(::grpc::ServerContext* context, const ::Array* request, ::Array* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


