// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: darcy.proto
// Protobuf C++ Version: 5.27.2

#include "darcy.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Array::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : val_{},
        n_cols_{0},
        n_rows_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Array::Array(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ArrayDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArrayDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArrayDefaultTypeInternal() {}
  union {
    Array _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArrayDefaultTypeInternal _Array_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_darcy_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_darcy_2eproto = nullptr;
const ::uint32_t
    TableStruct_darcy_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Array, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Array, _impl_.n_cols_),
        PROTOBUF_FIELD_OFFSET(::Array, _impl_.n_rows_),
        PROTOBUF_FIELD_OFFSET(::Array, _impl_.val_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Array)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Array_default_instance_._instance,
};
const char descriptor_table_protodef_darcy_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013darcy.proto\"4\n\005Array\022\016\n\006n_cols\030\001 \001(\005\022\016"
    "\n\006n_rows\030\002 \001(\005\022\013\n\003val\030\003 \003(\0012(\n\004piml\022 \n\014g"
    "et_residual\022\006.Array\032\006.Array\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_darcy_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_darcy_2eproto = {
    false,
    false,
    117,
    descriptor_table_protodef_darcy_2eproto,
    "darcy.proto",
    &descriptor_table_darcy_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_darcy_2eproto::offsets,
    file_level_enum_descriptors_darcy_2eproto,
    file_level_service_descriptors_darcy_2eproto,
};
// ===================================================================

class Array::_Internal {
 public:
};

Array::Array(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Array)
}
inline PROTOBUF_NDEBUG_INLINE Array::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Array& from_msg)
      : val_{visibility, arena, from.val_},
        _cached_size_{0} {}

Array::Array(
    ::google::protobuf::Arena* arena,
    const Array& from)
    : ::google::protobuf::Message(arena) {
  Array* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, n_cols_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, n_cols_),
           offsetof(Impl_, n_rows_) -
               offsetof(Impl_, n_cols_) +
               sizeof(Impl_::n_rows_));

  // @@protoc_insertion_point(copy_constructor:Array)
}
inline PROTOBUF_NDEBUG_INLINE Array::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : val_{visibility, arena},
        _cached_size_{0} {}

inline void Array::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, n_cols_),
           0,
           offsetof(Impl_, n_rows_) -
               offsetof(Impl_, n_cols_) +
               sizeof(Impl_::n_rows_));
}
Array::~Array() {
  // @@protoc_insertion_point(destructor:Array)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Array::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Array::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Array, _impl_._cached_size_),
              false,
          },
          &Array::MergeImpl,
          &Array::kDescriptorMethods,
          &descriptor_table_darcy_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Array::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Array_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Array>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 n_cols = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Array, _impl_.n_cols_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Array, _impl_.n_cols_)}},
    // int32 n_rows = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Array, _impl_.n_rows_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Array, _impl_.n_rows_)}},
    // repeated double val = 3;
    {::_pbi::TcParser::FastF64P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Array, _impl_.val_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 n_cols = 1;
    {PROTOBUF_FIELD_OFFSET(Array, _impl_.n_cols_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 n_rows = 2;
    {PROTOBUF_FIELD_OFFSET(Array, _impl_.n_rows_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated double val = 3;
    {PROTOBUF_FIELD_OFFSET(Array, _impl_.val_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Array::Clear() {
// @@protoc_insertion_point(message_clear_start:Array)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.val_.Clear();
  ::memset(&_impl_.n_cols_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.n_rows_) -
      reinterpret_cast<char*>(&_impl_.n_cols_)) + sizeof(_impl_.n_rows_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Array::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Array)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 n_cols = 1;
  if (this->_internal_n_cols() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_n_cols(), target);
  }

  // int32 n_rows = 2;
  if (this->_internal_n_rows() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_n_rows(), target);
  }

  // repeated double val = 3;
  if (this->_internal_val_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_val(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Array)
  return target;
}

::size_t Array::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Array)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated double val = 3;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_val_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // int32 n_cols = 1;
  if (this->_internal_n_cols() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_n_cols());
  }

  // int32 n_rows = 2;
  if (this->_internal_n_rows() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_n_rows());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Array::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Array*>(&to_msg);
  auto& from = static_cast<const Array&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Array)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_val()->MergeFrom(from._internal_val());
  if (from._internal_n_cols() != 0) {
    _this->_impl_.n_cols_ = from._impl_.n_cols_;
  }
  if (from._internal_n_rows() != 0) {
    _this->_impl_.n_rows_ = from._impl_.n_rows_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Array::CopyFrom(const Array& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Array)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Array::InternalSwap(Array* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.val_.InternalSwap(&other->_impl_.val_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Array, _impl_.n_rows_)
      + sizeof(Array::_impl_.n_rows_)
      - PROTOBUF_FIELD_OFFSET(Array, _impl_.n_cols_)>(
          reinterpret_cast<char*>(&_impl_.n_cols_),
          reinterpret_cast<char*>(&other->_impl_.n_cols_));
}

::google::protobuf::Metadata Array::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_darcy_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
